#!/usr/bin/env php
<?php
/*
 * This file is part of the Airlines package.
 *
 * (c) Matthias Vandermaesen <matthias@colada.be>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
// set to run indefinitely if needed
set_time_limit(0);
// Set the default timezone
date_default_timezone_set('Europe/Brussels');

$number = 1000;


        $carry = $number % 97;
        $carry = ($carry > 0) ? $carry : 97;

        $number = str_pad($number, 10, 0, STR_PAD_LEFT);
        $carry = str_pad($carry, 2, 0, STR_PAD_LEFT);

        $structuredMessage = $number . $carry;

        $pattern = array('/^([0-9]{3})([0-9]{4})([0-9]{5})$/');
        $replace = array('+++$1/$2/$3+++');
        $structuredMessage = preg_replace($pattern, $replace, $structuredMessage);

        print $structuredMessage;
